name: build

on:
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
          cache: true

      - name: Test
        run: go test -v ./...


  goreleaser:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
          cache: true

      - name: Run GoReleaser build and publish tags
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: migraterr
          path: dist/*
